// Build a single Windows executable (Node SEA — Single Executable Application).
//
//   npm run build:exe   →  dist-exe/虛擬員工系統.exe  (~90 MB, self-contained)
//
// Pipeline:
//   1. build the client (unless client/dist already exists)
//   2. embed client/dist into server/src/generated/client-assets.mjs
//   3. esbuild-bundle the ESM server into ONE CommonJS file (SEA needs CJS);
//      import.meta.url is shimmed to the exe path
//   4. generate the SEA blob (node --experimental-sea-config)
//   5. copy this machine's node.exe and inject the blob with postject
//   6. restore the client-assets stub so the repo stays clean
//
// The exe keeps its data in ./veemp-data/ NEXT TO itself (see util/portable.js)
// and auto-seeds the default team on first boot (see index.js). MarkItDown
// (PDF/DOCX parsing) and the optional embeddings model are source-install
// features — the exe falls back gracefully (TXT/MD/HTML upload still works).
import { execFileSync, execSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const cd = (...p) => path.join(root, ...p);
const run = (cmd, args, opts = {}) =>
  execFileSync(cmd, args, { stdio: 'inherit', cwd: root, ...opts });

const STUB = `// STUB — real content is generated by scripts/build-exe.mjs at exe-build time
// (an asset map of the built client: { '/index.html': { type, b64 }, … }) and
// restored to this null stub afterwards. In a source checkout this stays null
// and the app serves client/dist via express.static as usual.
export default null;
`;
const ASSETS_MJS = cd('server', 'src', 'generated', 'client-assets.mjs');

const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.ico': 'image/x-icon',
  '.json': 'application/json; charset=utf-8',
  '.txt': 'text/plain; charset=utf-8',
  '.woff2': 'font/woff2',
};

function collectAssets(dir, base = '') {
  const out = {};
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const abs = path.join(dir, e.name);
    const rel = `${base}/${e.name}`;
    if (e.isDirectory()) Object.assign(out, collectAssets(abs, rel));
    else {
      out[rel] = {
        type: MIME[path.extname(e.name).toLowerCase()] || 'application/octet-stream',
        b64: fs.readFileSync(abs).toString('base64'),
      };
    }
  }
  return out;
}

try {
  // ── 1) client build ────────────────────────────────────────────────────────
  if (!fs.existsSync(cd('client', 'dist', 'index.html'))) {
    console.log('→ 建置前端…');
    run(process.platform === 'win32' ? 'npm.cmd' : 'npm', ['run', 'build']);
  }

  // ── 2) embed the client ────────────────────────────────────────────────────
  console.log('→ 內嵌前端靜態檔…');
  const assets = collectAssets(cd('client', 'dist'));
  fs.writeFileSync(
    ASSETS_MJS,
    `// GENERATED by scripts/build-exe.mjs — do not commit real content.\nexport default ${JSON.stringify(assets)};\n`,
  );
  console.log(`  ${Object.keys(assets).length} 個檔案內嵌`);

  // ── 3) bundle the server to one CJS file ───────────────────────────────────
  console.log('→ esbuild 打包伺服器…');
  const esbuild = await import('esbuild'); // ships with vite — no extra dep
  fs.mkdirSync(cd('build', 'sea'), { recursive: true });
  await esbuild.build({
    entryPoints: [cd('server', 'src', 'index.js')],
    outfile: cd('build', 'sea', 'bundle.cjs'),
    bundle: true,
    platform: 'node',
    format: 'cjs',
    target: 'node22',
    // Optional dependency loaded via dynamic import inside try/catch — the exe
    // simply reports embeddings unavailable (pure-BM25 retrieval, as designed).
    external: ['@huggingface/transformers'],
    // ESM sources use import.meta.url; in the CJS bundle map it to __filename
    // (which, under SEA, is the exe path — exactly what config/portable want).
    define: { 'import.meta.url': '__veemp_import_meta_url' },
    banner: { js: `var __veemp_import_meta_url = require('node:url').pathToFileURL(__filename).href;` },
    logLevel: 'warning',
  });

  // ── 4) SEA blob ────────────────────────────────────────────────────────────
  console.log('→ 產生 SEA blob…');
  fs.writeFileSync(cd('build', 'sea', 'sea-config.json'), JSON.stringify({
    main: 'build/sea/bundle.cjs',
    output: 'build/sea/sea.blob',
    disableExperimentalSEAWarning: true,
  }, null, 2));
  run(process.execPath, ['--experimental-sea-config', 'build/sea/sea-config.json']);

  // ── 5) copy node.exe + inject ──────────────────────────────────────────────
  console.log('→ 注入 node 執行檔…');
  fs.mkdirSync(cd('dist-exe'), { recursive: true });
  const exePath = cd('dist-exe', '虛擬員工系統.exe');
  fs.copyFileSync(process.execPath, exePath);
  execSync(
    `npx --yes postject "${exePath}" NODE_SEA_BLOB build/sea/sea.blob --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2`,
    { stdio: 'inherit', cwd: root },
  );

  const mb = (fs.statSync(exePath).size / 1024 / 1024).toFixed(0);
  console.log(`\n✓ 完成：dist-exe\\虛擬員工系統.exe（約 ${mb} MB）`);
  console.log('  雙擊即用；資料存在 exe 旁的 veemp-data\\ 資料夾。');
} finally {
  // ── 6) always restore the stub so the repo never carries generated blobs ──
  fs.writeFileSync(ASSETS_MJS, STUB);
}
